/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "LiteDAOfactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiteDAOfactory__factory>;
    getContractFactory(
      name: "LiteDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiteDAO__factory>;
    getContractFactory(
      name: "LiteDAOnftHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiteDAOnftHelper__factory>;
    getContractFactory(
      name: "LiteDAOtoken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiteDAOtoken__factory>;

    getContractAt(
      name: "LiteDAOfactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LiteDAOfactory>;
    getContractAt(
      name: "LiteDAO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LiteDAO>;
    getContractAt(
      name: "LiteDAOnftHelper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LiteDAOnftHelper>;
    getContractAt(
      name: "LiteDAOtoken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LiteDAOtoken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
